# fly.toml app configuration file generated for my-fly-devbox-jasbahr on 2025-07-22T17:08:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-fly-devbox-jasbahr'
primary_region = 'ewr'

[build]

[mounts]
  source = "devbox_data"
  destination = "/data"

[[services]]
  internal_port = 22
  protocol = "tcp"
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  idle_timeout = "1h"
  [[services.ports]]
    port = 2222

[[services]]
  internal_port = 60000
  protocol = "udp"
  [[services.ports]]
    port = 60000

[[services]]
  internal_port = 61000
  protocol = "udp"
  [[services.ports]]
    port = 61000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
